//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Spinit.Stack.CMS.GeneratedModels
{
	/// <summary>Base Page</summary>
	[PublishedContentModel("basePage")]
	public partial class BasePage : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "basePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BasePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BasePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Body Text
		///</summary>
		[ImplementPropertyType("bodyText")]
		public Our.Umbraco.Vorto.Models.VortoValue BodyText
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue>("bodyText"); }
		}

		///<summary>
		/// Meta Description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public Our.Umbraco.Vorto.Models.VortoValue MetaDescription
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue>("metaDescription"); }
		}

		///<summary>
		/// Meta Title
		///</summary>
		[ImplementPropertyType("metaTitle")]
		public Our.Umbraco.Vorto.Models.VortoValue MetaTitle
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue>("metaTitle"); }
		}

		///<summary>
		/// Page Title
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public Our.Umbraco.Vorto.Models.VortoValue PageTitle
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue>("pageTitle"); }
		}

		///<summary>
		/// Sub Heading
		///</summary>
		[ImplementPropertyType("subHeading")]
		public Our.Umbraco.Vorto.Models.VortoValue SubHeading
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue>("subHeading"); }
		}
	}
}
